DocWorks for panel-elements - 3 changes detected, but 73 issue detected changes: Service $w.PanelButton was removed Service $w.PanelRichText was removed Service $w.PanelToggleSwitch was removed
issues:
Operation onChange has an unknown param type $w.EventHandler (PanelCheckboxGroup.js (132))
Operation onChange has an unknown return type $w.Element (PanelCheckboxGroup.js (132))
Mixin $w.HiddenCollapsedMixin not found (PanelCheckboxGroup.js (1))
Operation onChange has an unknown param type $w.EventHandler (PanelDropdown.js (151))
Operation onChange has an unknown return type $w.Element (PanelDropdown.js (151))
Mixin $w.HiddenCollapsedMixin not found (PanelDropdown.js (1))
Operation onChange has an unknown param type $w.EventHandler (PanelRadioButtonGroup.js (131))
Operation onChange has an unknown return type $w.Element (PanelRadioButtonGroup.js (131))
Mixin $w.HiddenCollapsedMixin not found (PanelRadioButtonGroup.js (1))
Mixin $w.HiddenCollapsedMixin not found (PanelSectionDivider.js (1))
Operation onChange has an unknown param type $w.EventHandler (PanelSlider.js (213))
Operation onChange has an unknown return type $w.Element (PanelSlider.js (213))
Property value has mismatching types for get (number) and set (string) (PanelSlider.js (14, 29))
Mixin $w.HiddenCollapsedMixin not found (PanelSlider.js (1))
Operation onChange has an unknown param type $w.EventHandler (PanelTextInput.js (283))
Operation onChange has an unknown return type $w.Element (PanelTextInput.js (283))
Mixin $w.HiddenCollapsedMixin not found (PanelTextInput.js (1))
Operation onChange has an unknown param type $w.EventHandler (PanelThumbnails.js (222))
Operation onChange has an unknown return type $w.Element (PanelThumbnails.js (222))
Property options has mismatching types for get ([object Object]) and set ([object Object]) (PanelThumbnails.js (183, 197))
Mixin $w.HiddenCollapsedMixin not found (PanelThumbnails.js (1))
ERROR: The @snippet tag - file 'velo-docs/examples/PanelElements-divider_get.es6 ...