DocWorks for panel-elements - 2 changes detected, but 36 issue detected changes: Service $w.PanelThumbnails message illustration member undefined was removed Service $w.PanelThumbnails message option member undefined was removed
issues:
Mixin $w.HiddenCollapsedMixin not found (PanelSectionDivider.js (1))
Operation onChange has an unknown param type $w.EventHandler (PanelTextInput.js (283))
Operation onChange has an unknown return type $w.Element (PanelTextInput.js (283))
Mixin $w.HiddenCollapsedMixin not found (PanelTextInput.js (1))
Operation onChange has an unknown param type $w.EventHandler (PanelThumbnails.js (222))
Operation onChange has an unknown return type $w.Element (PanelThumbnails.js (222))
Property options has mismatching types for get ([object Object]) and set ([object Object]) (PanelThumbnails.js (183, 197))
Mixin $w.HiddenCollapsedMixin not found (PanelThumbnails.js (1))
ERROR: The @snippet tag - file 'velo-docs/examples/PanelElements-divider_get.es6' not found. File: PanelTextInput.js line: 92
ERROR: The @snippet tag - file 'velo-docs/examples/PanelElements-divider_set.es6' not found. File: PanelTextInput.js line: 92
ERROR: The @snippet tag - file 'velo-docs/examples/panelTextInput/PanelTextInput-readOnly_get.es6' not found. File: PanelTextInput.js line: 133
ERROR: The @snippet tag - file 'velo-docs/examples/panelTextInput/PanelTextInput-readOnly_set.es6' not found. File: PanelTextInput.js line: 133
ERROR: The @snippet tag - file 'velo-docs/examples/panelTextInput/PanelTextInput-autoFocus_get.es6' not found. File: PanelTextInput.js line: 151
ERROR: The @snippet tag - file 'velo-docs/examples/panelTextInput/PanelTextInput-autoFocus_set.es6' not found. File: PanelTextInput.js line: 151
ERROR: The @snippet tag - file 'velo-docs/examples/panelTextInput/PanelTextInput-selectTextOnFocus_get.es6' not found. File: PanelTextInput.js line: 169
ERROR: The @snippet tag - file 'velo-docs/examples/panelTextInput/PanelTextInput-selectTextOnFocus_set.es6' not foun ...